icons_format = "{icon}"

[icons]
icons = "material-nf"
#[icons.overrides]
#bat = ["|E|", "|_|", "|=|", "|F|"]
#bat_charging = "|^| "
#volume = ["|v|", "|V|"]
#volume_muted = "|M|"
#headphones = "|H|"
#backlight = "|B|"
#scratchpad = "|S|"
#tea = "|T|"


[[block]]
block = "music"

[[block]]
block = "scratchpad"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"

[[block]]
block = "battery"

[[block]]
block = "net"
format = " $icon "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
