#!/bin/sh
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.
#
# riverctl spawn "xwayland-satellite"

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.
riverctl map normal Super Return spawn alacritty
riverctl map normal Super+Shift Q close
riverctl map normal Super+Shift+Control Q exit

riverctl map normal Super Slash spawn wmenu-run
riverctl map normal Super M spawn dmount.sh
riverctl map normal Super+Shift M  spawn dumount.sh
riverctl map normal Super O spawn doffice.sh
riverctl map normal Super P spawn dproject.sh
riverctl map normal Super B spawn floorp

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
# riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done
scratch_tag=$((1 << 20 ))
riverctl map normal Super S toggle-focused-tags ${scratch_tag}		# toggle the scratchpad
riverctl map normal Super+Shift S set-view-tags ${scratch_tag}		# send windows to the scratchpad

# Set spawn tagmask to ensure new windows do not have the scratchpad tag unless explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_but_scratch_tag
riverctl map normal Super+Shift 0 set-view-tags $all_but_scratch_tag

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+"
    riverctl map $mode None XF86AudioLowerVolume  spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-"
    riverctl map $mode None XF86AudioMute         spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
    riverctl map $mode None XF86AudioMicMute      spawn "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
    riverctl map $mode None XF86AudioPlay         spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPrev         spawn "playerctl previous"
    riverctl map $mode None XF86AudioNext         spawn "playerctl next"
    riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl set 5%-"
    riverctl map $mode None XF86MonBrightnessUp   spawn "brightnessctl set 5%+"
done

# Set background and border color
riverctl border-color-unfocused 0x586e75
riverctl border-color-focused 0xebbcba

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
# riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add ssd
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.

riverctl default-attach-mode below
riverctl default-layout rivertile
rivertile -main-ratio 0.5 -view-padding 2 -outer-padding 2 &
# riverctl default-layout wideriver
# ~/.local/wideriver/wideriver  --inner-gaps 3 --outer-gaps 3   --border-color-focused 0xebbcba \
#     --border-color-unfocused 0x586e75 --layout left --stack dwindle&

waybar &
nm-applet &
mako &
mpd-mpris &
wlsunset -s 21:00 -S 07:00 &
swayidle -C "$HOME/.config/swayidle.conf" &
swaybg -i "$HOME/.config/wallpapers/leafy-moon.png" &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
wlr-randr --output eDP-1 --scale  1.5 &
